services:
  mysql:
    image: 'mysql:lts'
    environment:
      - 'MYSQL_DATABASE=playground'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=choicore'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
